package com.multimotors.forms;

import com.multimotors.models.User;
import com.multimotors.models.Vehicle;
import com.multimotors.controllers.UsersController;
import com.multimotors.controllers.VehiclesController;
import java.awt.Component;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSlider;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 * @author Sergio 
 * @author Fabian 
 */
public class MainScreen extends javax.swing.JFrame {

    public MainScreen(int id_user) {
        initComponents();
        setLocationRelativeTo(null);
        init(id_user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_vehiculos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_marca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        slider_preciomax = new javax.swing.JSlider();
        txt_preciomax = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        slider_kmmax = new javax.swing.JSlider();
        txt_kmmax = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rb_diesel = new javax.swing.JRadioButton();
        rb_gasolina = new javax.swing.JRadioButton();
        rb_otro = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_categoria = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cb_tipo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        rb_automatica = new javax.swing.JRadioButton();
        rb_manual = new javax.swing.JRadioButton();
        slider_cvmax = new javax.swing.JSlider();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_cvmax = new javax.swing.JTextField();
        btn_filtrar = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jyc_min = new com.toedter.calendar.JYearChooser();
        jyc_max = new com.toedter.calendar.JYearChooser();
        jPanel1 = new javax.swing.JPanel();
        btn_myacc = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        tb_vehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_vehiculos.setRowHeight(50);
        tb_vehiculos.setRowMargin(5);
        tb_vehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_vehiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_vehiculos);

        jPanel3.add(jScrollPane1);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 750, 620));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(73, 80, 87));
        jLabel2.setText("Marca");
        jLabel2.setMaximumSize(new java.awt.Dimension(21, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(21, 16));
        jLabel2.setPreferredSize(new java.awt.Dimension(21, 16));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 20));
        jPanel2.add(txt_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, 30));

        jLabel3.setForeground(new java.awt.Color(73, 80, 87));
        jLabel3.setText("Modelo");
        jLabel3.setMaximumSize(new java.awt.Dimension(21, 16));
        jLabel3.setMinimumSize(new java.awt.Dimension(21, 16));
        jLabel3.setPreferredSize(new java.awt.Dimension(21, 16));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, 20));
        jPanel2.add(txt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 210, 30));

        jLabel8.setForeground(new java.awt.Color(73, 80, 87));
        jLabel8.setText("Precio Max.");
        jLabel8.setMaximumSize(new java.awt.Dimension(21, 16));
        jLabel8.setMinimumSize(new java.awt.Dimension(21, 16));
        jLabel8.setPreferredSize(new java.awt.Dimension(21, 16));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, -1));

        slider_preciomax.setBackground(new java.awt.Color(204, 204, 204));
        slider_preciomax.setMaximum(1000000);
        slider_preciomax.setMinimum(20000);
        slider_preciomax.setPaintTicks(true);
        slider_preciomax.setToolTipText("");
        slider_preciomax.setValue(500000);
        slider_preciomax.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                slider_preciomaxMouseDragged(evt);
            }
        });
        jPanel2.add(slider_preciomax, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txt_preciomax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_preciomaxActionPerformed(evt);
            }
        });
        jPanel2.add(txt_preciomax, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 80, 30));

        jLabel6.setForeground(new java.awt.Color(73, 80, 87));
        jLabel6.setText("Kilometros Max.");
        jLabel6.setMaximumSize(new java.awt.Dimension(21, 16));
        jLabel6.setMinimumSize(new java.awt.Dimension(21, 16));
        jLabel6.setPreferredSize(new java.awt.Dimension(21, 16));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 100, -1));

        slider_kmmax.setBackground(new java.awt.Color(204, 204, 204));
        slider_kmmax.setMaximum(400000);
        slider_kmmax.setPaintTicks(true);
        slider_kmmax.setValue(200000);
        slider_kmmax.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                slider_kmmaxMouseDragged(evt);
            }
        });
        jPanel2.add(slider_kmmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txt_kmmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kmmaxActionPerformed(evt);
            }
        });
        jPanel2.add(txt_kmmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 80, 30));

        jLabel5.setForeground(new java.awt.Color(73, 80, 87));
        jLabel5.setText("Combustible");
        jLabel5.setMaximumSize(new java.awt.Dimension(21, 16));
        jLabel5.setMinimumSize(new java.awt.Dimension(21, 16));
        jLabel5.setPreferredSize(new java.awt.Dimension(21, 16));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 90, -1));

        rb_diesel.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rb_diesel);
        rb_diesel.setForeground(new java.awt.Color(73, 80, 87));
        rb_diesel.setText("Diesel");
        jPanel2.add(rb_diesel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 98, -1));

        rb_gasolina.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rb_gasolina);
        rb_gasolina.setForeground(new java.awt.Color(73, 80, 87));
        rb_gasolina.setText("Gasolina");
        jPanel2.add(rb_gasolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 98, -1));

        rb_otro.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rb_otro);
        rb_otro.setForeground(new java.awt.Color(73, 80, 87));
        rb_otro.setText("Otro");
        jPanel2.add(rb_otro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 98, -1));

        jLabel7.setForeground(new java.awt.Color(73, 80, 87));
        jLabel7.setText("Desde");
        jLabel7.setMaximumSize(new java.awt.Dimension(21, 16));
        jLabel7.setMinimumSize(new java.awt.Dimension(21, 16));
        jLabel7.setPreferredSize(new java.awt.Dimension(21, 16));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 60, 20));

        jLabel9.setForeground(new java.awt.Color(73, 80, 87));
        jLabel9.setText("Categoria");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, -1, -1));

        jPanel2.add(cb_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 120, 30));

        jLabel10.setForeground(new java.awt.Color(73, 80, 87));
        jLabel10.setText("Tipo");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        cb_tipo.setForeground(new java.awt.Color(73, 80, 87));
        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Coche", "Moto" }));
        cb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipoActionPerformed(evt);
            }
        });
        jPanel2.add(cb_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 120, 30));

        jLabel11.setForeground(new java.awt.Color(73, 80, 87));
        jLabel11.setText("Tipo de transmision");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        rb_automatica.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup2.add(rb_automatica);
        rb_automatica.setForeground(new java.awt.Color(73, 80, 87));
        rb_automatica.setText("Automatica");
        jPanel2.add(rb_automatica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 98, -1));

        rb_manual.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup2.add(rb_manual);
        rb_manual.setForeground(new java.awt.Color(73, 80, 87));
        rb_manual.setText("Manual");
        jPanel2.add(rb_manual, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 98, -1));

        slider_cvmax.setBackground(new java.awt.Color(204, 204, 204));
        slider_cvmax.setMaximum(1000);
        slider_cvmax.setMinimum(90);
        slider_cvmax.setPaintTicks(true);
        slider_cvmax.setValue(545);
        slider_cvmax.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                slider_cvmaxMouseDragged(evt);
            }
        });
        jPanel2.add(slider_cvmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel12.setForeground(new java.awt.Color(73, 80, 87));
        jLabel12.setText("Potencia del motor Max.");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel13.setForeground(new java.awt.Color(73, 80, 87));
        jLabel13.setText("Hasta");
        jLabel13.setMaximumSize(new java.awt.Dimension(21, 16));
        jLabel13.setMinimumSize(new java.awt.Dimension(21, 16));
        jLabel13.setPreferredSize(new java.awt.Dimension(21, 16));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 60, 20));

        txt_cvmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cvmaxActionPerformed(evt);
            }
        });
        jPanel2.add(txt_cvmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 80, 30));

        btn_filtrar.setBackground(new java.awt.Color(204, 204, 204));
        btn_filtrar.setText("FILTRAR");
        btn_filtrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filtrarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_filtrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 130, 40));

        btn_clear.setBackground(new java.awt.Color(204, 204, 204));
        btn_clear.setText("LIMPIAR CAMPOS");
        btn_clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel2.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, 130, 40));

        jyc_min.setYear(1950);
        jPanel2.add(jyc_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 80, 30));
        jPanel2.add(jyc_max, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 80, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 490, 670));

        jPanel1.setBackground(new java.awt.Color(244, 243, 243));
        jPanel1.setForeground(new java.awt.Color(60, 63, 65));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_myacc.setBackground(new java.awt.Color(255, 153, 255));
        btn_myacc.setText("MI CUENTA");
        btn_myacc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_myacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_myaccActionPerformed(evt);
            }
        });
        jPanel1.add(btn_myacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 670, 390, 40));

        btn_login.setBackground(new java.awt.Color(255, 153, 255));
        btn_login.setText("INICIAR SESION");
        btn_login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 670, 390, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/myacc_wp.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slider_preciomaxMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider_preciomaxMouseDragged
        sliderValue(txt_preciomax, slider_preciomax);
    }//GEN-LAST:event_slider_preciomaxMouseDragged

    private void slider_kmmaxMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider_kmmaxMouseDragged
        sliderValue(txt_kmmax, slider_kmmax);
    }//GEN-LAST:event_slider_kmmaxMouseDragged

    private void slider_cvmaxMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider_cvmaxMouseDragged
        sliderValue(txt_cvmax, slider_cvmax);
    }//GEN-LAST:event_slider_cvmaxMouseDragged

    private void txt_preciomaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_preciomaxActionPerformed
        maxFilter(txt_preciomax, slider_preciomax);
    }//GEN-LAST:event_txt_preciomaxActionPerformed

    private void txt_kmmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kmmaxActionPerformed
        maxFilter(txt_kmmax, slider_kmmax);
    }//GEN-LAST:event_txt_kmmaxActionPerformed

    private void txt_cvmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cvmaxActionPerformed
        maxFilter(txt_cvmax, slider_cvmax);
    }//GEN-LAST:event_txt_cvmaxActionPerformed

    private void cb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipoActionPerformed
        cambiarCategoria();
    }//GEN-LAST:event_cb_tipoActionPerformed

    private void btn_myaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_myaccActionPerformed
        myAccountScreen();
    }//GEN-LAST:event_btn_myaccActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        loginScreen();
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filtrarActionPerformed
        filtrarCoches();
    }//GEN-LAST:event_btn_filtrarActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void tb_vehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_vehiculosMouseClicked
        vehicleScreen();
    }//GEN-LAST:event_tb_vehiculosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_filtrar;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_myacc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb_categoria;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JYearChooser jyc_max;
    private com.toedter.calendar.JYearChooser jyc_min;
    private javax.swing.JRadioButton rb_automatica;
    private javax.swing.JRadioButton rb_diesel;
    private javax.swing.JRadioButton rb_gasolina;
    private javax.swing.JRadioButton rb_manual;
    private javax.swing.JRadioButton rb_otro;
    private javax.swing.JSlider slider_cvmax;
    private javax.swing.JSlider slider_kmmax;
    private javax.swing.JSlider slider_preciomax;
    private javax.swing.JTable tb_vehiculos;
    private javax.swing.JTextField txt_cvmax;
    private javax.swing.JTextField txt_kmmax;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_preciomax;
    // End of variables declaration//GEN-END:variables

    private int id_user;
    private String sWhere = "";
    private VehiclesController vehicleDAO;
    private HashMap<Integer, Vehicle> vehicles;
    private User user = null;

    private void init(int id_user) {
        this.vehicleDAO = new VehiclesController();
        this.vehicles = vehicleDAO.readAll();
        this.btn_myacc.setVisible(false);
        if (id_user == -1){mantenerSesionIniciada();}
        login(id_user);
        iniciarTabla();
    }

    private void iniciarTabla() {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        modelo.addColumn("ID");
        modelo.addColumn("Vehiculo");
        modelo.addColumn("Combustible");
        modelo.addColumn("Kilometros");
        modelo.addColumn("Transmision");
        modelo.addColumn("Potencia");
        modelo.addColumn("Precio");

        for (Vehicle vehicle : vehicles.values()) {
            Object[] fila = new Object[7];
            fila[0] = vehicle.getId();
            fila[1] = vehicle.getBrand() + " " + vehicle.getModel();
            fila[2] = vehicle.getSpecs().getFuel_type();
            fila[3] = vehicle.getSpecs().getKilometres();
            fila[4] = vehicle.getSpecs().getTransmission_type();
            fila[5] = vehicle.getSpecs().getEngine_cc();
            fila[6] = vehicle.getPrice();
            modelo.addRow(fila);
        }
        tb_vehiculos.setModel(modelo);
        resizeColumnWidth(tb_vehiculos);

        for (int i = 0; i < tb_vehiculos.getColumnCount(); i++) {
            tb_vehiculos.getColumnModel().getColumn(i).setCellRenderer(tcr);
        }
        tb_vehiculos.getColumnModel().getColumn(0).setMaxWidth(0);
        tb_vehiculos.getColumnModel().getColumn(0).setMinWidth(0);
        tb_vehiculos.getColumnModel().getColumn(0).setPreferredWidth(0);
        tb_vehiculos.getColumnModel().getColumn(0).setResizable(false);
    }

    private void resizeColumnWidth(JTable table) {
        TableColumnModel columnModel = table.getColumnModel();

        for (int column = 0; column < table.getColumnCount(); column++) {
            int width = 150;

            for (int row = 0; row < table.getRowCount(); row++) {
                TableCellRenderer renderer = table.getCellRenderer(row, column);
                Component comp = table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width + 1, width);
            }
            if (width > 300) {
                width = 300;
            }
            columnModel.getColumn(column).setPreferredWidth(width);
        }
    }

    private void cambiarCategoria() {
        ArrayList<String> categoria_coches = new ArrayList<>();
        categoria_coches.add("");
        categoria_coches.add("Suv");
        categoria_coches.add("Sedan");
        categoria_coches.add("Clasico");
        categoria_coches.add("Deportivo");
        categoria_coches.add("Superdeportivo");

        ArrayList<String> categoria_motos = new ArrayList<>();
        categoria_motos.add("");
        categoria_motos.add("Naked");
        categoria_motos.add("Montaña");
        categoria_motos.add("Circuito");
        categoria_motos.add("Deportiva");

        switch (cb_tipo.getSelectedIndex()) {
            case 1:
                rellenarCategoria(categoria_coches);
                break;
            case 2:
                rellenarCategoria(categoria_motos);
                break;
            default:
                cb_categoria.removeAllItems();
                break;
        }
    }

    private void rellenarCategoria(ArrayList<String> categorias) {
        cb_categoria.removeAllItems();
        for (int i = 0; i < categorias.size(); i++) {
            cb_categoria.addItem(categorias.get(i));
        }
    }

    private void login(int id_user) {
        if (id_user > 0) {
            this.id_user = id_user;
            user = new UsersController().readUser(this.id_user);
            btn_login.setVisible(false);
            btn_myacc.setVisible(true);
        }
    }

    private void mantenerSesionIniciada() {
        String id = new Login(this, false).getid();
        if (!id.equals("")) {
            login(Integer.parseInt(id));
        }

    }

    public void actualizarTabla() {
        vehicles = vehicleDAO.readAll();
        iniciarTabla();
    }

    public void cerrarFrame() {
        this.setVisible(false);
    }

    private void loginScreen() {
        Login l = new Login(this, false);
        l.setVisible(true);
    }

    private void myAccountScreen() {
        MyAccount a = new MyAccount(this, false, id_user);
        a.setVisible(true);
    }

    private void vehicleScreen() { 
        int id = Integer.parseInt(String.valueOf(tb_vehiculos.getValueAt(tb_vehiculos.getSelectedRow(), 0)));
        if (user != null) {
            ScreenVehicle screenVehicle = new ScreenVehicle(this, false, id, user);
            screenVehicle.setVisible(true);
        } else {
            ScreenVehicle screenVehicle = new ScreenVehicle(this, false, id);
            screenVehicle.setVisible(true);
        } 
    }

    private void maxFilter(JTextField textfield, JSlider slider) {
        if (Integer.parseInt(textfield.getText()) > slider.getMaximum()) {
            textfield.setText(String.valueOf(slider.getMaximum()));
        } else if (Integer.parseInt(textfield.getText()) < slider.getMinimum()) {
            textfield.setText(String.valueOf(slider.getMinimum()));
        }
        slider.setValue(Integer.parseInt(textfield.getText()));
    }

    private void sliderValue(JTextField textfield, JSlider slider) {
        textfield.setText(String.valueOf(slider.getValue()));
    }

    private void filtrarCoches() {
        try {
            sWhere = "";
            
            if (txt_marca.getText() != null && !txt_marca.getText().contentEquals("")) {
                sWhere = sWhere + " VCL.brand LIKE '%" + txt_marca.getText() + "%'";
            }
            if (txt_modelo.getText() != null && !txt_modelo.getText().contentEquals("")) {
                if (!sWhere.contentEquals("")) {
                    sWhere = sWhere + " AND";
                }
                sWhere = sWhere + " VCL.model LIKE '%" + txt_modelo.getText() + "%'";
            }
            if (txt_preciomax.getText() != null && !txt_preciomax.getText().contentEquals("")) {
                if (!sWhere.contentEquals("")) {
                    sWhere = sWhere + " AND";
                }
                sWhere = sWhere + " VCL.price <=" + txt_preciomax.getText();
            }
            if (rb_diesel.isSelected()) {
                if (!sWhere.contentEquals("")) {
                    sWhere = sWhere + " AND";
                }
                sWhere = sWhere + " SPC.fuel_type LIKE '%" + rb_diesel.getText() + "%'";
            }
            if (rb_gasolina.isSelected()) {
                if (!sWhere.contentEquals("")) {
                    sWhere = sWhere + " AND";
                }
                sWhere = sWhere + " fuel_type LIKE '%" + rb_gasolina.getText() + "%'";
            }
            if (rb_otro.isSelected()) {
                if (!sWhere.contentEquals("")) {
                    sWhere = sWhere + " AND";
                }
                sWhere = sWhere + " SPC.fuel_type LIKE '%" + rb_otro.getText() + "%'";
            }
            if (txt_kmmax.getText() != null && !txt_kmmax.getText().contentEquals("")) {
                if (!sWhere.contentEquals("")) {
                    sWhere = sWhere + " AND";
                }
                sWhere = sWhere + " SPC.kilometres <=" + txt_kmmax.getText();
            }
            if (cb_categoria.getSelectedItem() != null) {
                if (!sWhere.contentEquals("")) {
                    sWhere = sWhere + " AND";
                }
                sWhere = sWhere + " VCL.category LIKE '%" + cb_categoria.getSelectedItem().toString() + "%'";
            }
            if (cb_tipo.getSelectedItem() != null) {
                if (!sWhere.contentEquals("")) {
                    sWhere = sWhere + " AND";
                }
                sWhere = sWhere + " VCL.type LIKE '%" + cb_tipo.getSelectedItem().toString() + "%'";
            }
            if (rb_automatica.isSelected()) {
                if (!sWhere.contentEquals("")) {
                    sWhere = sWhere + " AND";
                }
                sWhere = sWhere + " SPC.transmission_type LIKE '%" + rb_automatica.getText() + "%'";
            }
            if (rb_manual.isSelected()) {
                if (!sWhere.contentEquals("")) {
                    sWhere = sWhere + " AND";
                }
                sWhere = sWhere + " SPC.transmission_type LIKE '%" + rb_manual.getText() + "%'";
            }
            if (txt_cvmax.getText() != null && !txt_cvmax.getText().contentEquals("")) {
                if (!sWhere.contentEquals("")) {
                    sWhere = sWhere + " AND";
                }
                sWhere = sWhere + " SPC.engine_cc <= " + txt_cvmax.getText();
            }
            if (jyc_min.getValue() > 1900 && jyc_max.getValue() < 2024) {
                if (!sWhere.contentEquals("")) {
                    sWhere = sWhere + " AND";
                }
                sWhere = sWhere + " SPC.model_year >= " + jyc_min.getValue() + " AND SPC.model_year <= " + jyc_max.getValue();
            }
            
            if (!sWhere.contentEquals("")) {
                sWhere = " WHERE" + sWhere + " AND VCL.status = 'Disponible'";
            }

            vehicles = vehicleDAO.readFilter(URLEncoder.encode(sWhere, "UTF-8"));
            iniciarTabla();
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void limpiarCampos() {
        sWhere = "";
        txt_marca.setText("");
        txt_cvmax.setText("");
        txt_kmmax.setText("");
        txt_modelo.setText("");
        txt_preciomax.setText("");
        slider_cvmax.setValue(slider_cvmax.getMaximum() / 2);
        slider_kmmax.setValue(slider_kmmax.getMaximum() / 2);
        slider_preciomax.setValue(slider_preciomax.getMaximum() / 2);
        cb_tipo.setSelectedIndex(0);
        cb_categoria.removeAllItems();
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        jyc_max.setValue(2023);
        jyc_min.setValue(1950);
        iniciarTabla();
    }
}