package com.multimotors.forms;

import com.multimotors.models.User;
import com.multimotors.controllers.UsersController;
import com.multimotors.utils.Utils;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.Pattern;

/**
 * @author Sergio 
 * @author Fabian 
 */
public class MyAccount extends javax.swing.JDialog {

    public MyAccount(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    public MyAccount(java.awt.Frame parent, boolean modal, int id_user) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        init(id_user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombrelog = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_mail = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        btn_cerrarsesion = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_tlf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_apel = new javax.swing.JTextField();
        btn_actualizar = new javax.swing.JButton();
        edit_otherInfo = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_nombre = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        edit_loginInfo = new javax.swing.JLabel();
        edit_personalInfo = new javax.swing.JLabel();
        txt_newpass = new javax.swing.JTextField();
        txt_passact = new javax.swing.JTextField();
        cb_genero = new javax.swing.JComboBox<>();
        cb_nacionalidad = new javax.swing.JComboBox<>();
        jdc_fnacimiento = new com.toedter.calendar.JDateChooser();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_ppal = new javax.swing.JButton();
        btn_favoritos = new javax.swing.JButton();
        btn_chatgpt = new javax.swing.JButton();
        btn_chatonline = new javax.swing.JButton();
        btn_miscoches = new javax.swing.JButton();
        btn_adminmode = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Avatar_Container.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jLabel3.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel3.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLabel3.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 110, 90));

        txt_nombrelog.setText("nombre ");
        txt_nombrelog.setMaximumSize(new java.awt.Dimension(1280, 720));
        txt_nombrelog.setMinimumSize(new java.awt.Dimension(1280, 720));
        txt_nombrelog.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel7.add(txt_nombrelog, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 60, 30));

        jLabel4.setText("Bienvenido");
        jLabel4.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel4.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLabel4.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 100, 30));

        txt_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });
        jPanel7.add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 210, 40));

        jLabel21.setForeground(new java.awt.Color(73, 80, 87));
        jLabel21.setText("Correo electrónico");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));
        jPanel7.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 760, 10));

        jLabel22.setForeground(new java.awt.Color(73, 80, 87));
        jLabel22.setText("Otra información personal");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        btn_cerrarsesion.setBackground(new java.awt.Color(255, 153, 255));
        btn_cerrarsesion.setText("CERRAR SESION");
        btn_cerrarsesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarsesionActionPerformed(evt);
            }
        });
        jPanel7.add(btn_cerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 280, 40));

        jLabel10.setForeground(new java.awt.Color(73, 80, 87));
        jLabel10.setText("Apellido");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));
        jPanel7.add(txt_tlf, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 210, 40));

        jLabel13.setForeground(new java.awt.Color(73, 80, 87));
        jLabel13.setText("Teléfono");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));
        jPanel7.add(txt_apel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 210, 40));

        btn_actualizar.setBackground(new java.awt.Color(255, 153, 255));
        btn_actualizar.setText("Actualizar");
        btn_actualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        jPanel7.add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, 390, 40));

        edit_otherInfo.setForeground(new java.awt.Color(73, 80, 87));
        edit_otherInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        edit_otherInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_otherInfoMouseClicked(evt);
            }
        });
        jPanel7.add(edit_otherInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 30, 30));

        jLabel20.setForeground(new java.awt.Color(73, 80, 87));
        jLabel20.setText("Nombre");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        jPanel7.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 760, 10));
        jPanel7.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 210, 40));

        jLabel24.setForeground(new java.awt.Color(73, 80, 87));
        jLabel24.setText("Fecha de nacimiento");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, -1));
        jPanel7.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 760, 10));

        jLabel25.setForeground(new java.awt.Color(73, 80, 87));
        jLabel25.setText("Nueva contraseña");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, -1, -1));

        edit_loginInfo.setForeground(new java.awt.Color(73, 80, 87));
        edit_loginInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        edit_loginInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_loginInfoMouseClicked(evt);
            }
        });
        jPanel7.add(edit_loginInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 30, 30));

        edit_personalInfo.setForeground(new java.awt.Color(73, 80, 87));
        edit_personalInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        edit_personalInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_personalInfoMouseClicked(evt);
            }
        });
        jPanel7.add(edit_personalInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 30, 30));

        txt_newpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Performed(evt);
            }
        });
        jPanel7.add(txt_newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 210, 40));
        jPanel7.add(txt_passact, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 210, 40));

        cb_genero.setForeground(new java.awt.Color(73, 80, 87));
        cb_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Otro" }));
        jPanel7.add(cb_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 210, 40));

        cb_nacionalidad.setForeground(new java.awt.Color(73, 80, 87));
        cb_nacionalidad.setToolTipText("");
        jPanel7.add(cb_nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 210, 40));
        jPanel7.add(jdc_fnacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 210, 40));

        jLabel26.setForeground(new java.awt.Color(73, 80, 87));
        jLabel26.setText("Contraseña actual");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, -1));

        jLabel27.setForeground(new java.awt.Color(73, 80, 87));
        jLabel27.setText("Información de login");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jLabel28.setForeground(new java.awt.Color(73, 80, 87));
        jLabel28.setText("Nacionalidad");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel29.setForeground(new java.awt.Color(73, 80, 87));
        jLabel29.setText("Genero");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        jLabel7.setForeground(new java.awt.Color(73, 80, 87));
        jLabel7.setText("Información personal");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Card_Content.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 450, 380));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Card_Content.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 130, 450, 380));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Card_Content.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 130, 450, 380));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Card_Content.png"))); // NOI18N
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 226, 450, 380));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Card_Content.png"))); // NOI18N
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 226, 450, 380));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Card_Content.png"))); // NOI18N
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 226, 450, 380));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 1050, 610));

        jPanel1.setBackground(new java.awt.Color(244, 243, 243));
        jPanel1.setForeground(new java.awt.Color(60, 63, 65));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ppal.setBackground(new java.awt.Color(255, 153, 255));
        btn_ppal.setText("Volver a la pantalla principal");
        btn_ppal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_ppal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ppalActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ppal, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 670, 390, 40));

        btn_favoritos.setBackground(new java.awt.Color(255, 153, 255));
        btn_favoritos.setText("Mis Favoritos");
        btn_favoritos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_favoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_favoritosActionPerformed(evt);
            }
        });
        jPanel1.add(btn_favoritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 350, 120, 50));

        btn_chatgpt.setBackground(new java.awt.Color(255, 153, 255));
        btn_chatgpt.setText("Asistente Virtual");
        btn_chatgpt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_chatgpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chatgptActionPerformed(evt);
            }
        });
        jPanel1.add(btn_chatgpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 170, 120, 50));

        btn_chatonline.setBackground(new java.awt.Color(255, 153, 255));
        btn_chatonline.setText("Chat General");
        btn_chatonline.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_chatonline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chatonlineActionPerformed(evt);
            }
        });
        jPanel1.add(btn_chatonline, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 230, 120, 50));

        btn_miscoches.setBackground(new java.awt.Color(255, 153, 255));
        btn_miscoches.setText("Mis Vehiculos");
        btn_miscoches.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_miscoches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_miscochesActionPerformed(evt);
            }
        });
        jPanel1.add(btn_miscoches, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 290, 120, 50));

        btn_adminmode.setBackground(new java.awt.Color(255, 153, 255));
        btn_adminmode.setText("Modo Admin");
        btn_adminmode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_adminmode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminmodeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_adminmode, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 410, 120, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ellipse 209.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/myacc_wp.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ppalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ppalActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_ppalActionPerformed

    private void btn_cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarsesionActionPerformed
        cerrarSesion();
    }//GEN-LAST:event_btn_cerrarsesionActionPerformed

    private void ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionPerformed
    }//GEN-LAST:event_ActionPerformed

    private void Performed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Performed
    }//GEN-LAST:event_Performed

    private void edit_personalInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_personalInfoMouseClicked
        editPersonalInfo();
    }//GEN-LAST:event_edit_personalInfoMouseClicked

    private void edit_otherInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_otherInfoMouseClicked
        editOtherInfo();
    }//GEN-LAST:event_edit_otherInfoMouseClicked

    private void edit_loginInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_loginInfoMouseClicked
        editLoginInfo();
    }//GEN-LAST:event_edit_loginInfoMouseClicked

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        actualizarUsuario();
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_favoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_favoritosActionPerformed
        favoritesScreen();
    }//GEN-LAST:event_btn_favoritosActionPerformed

    private void btn_chatgptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chatgptActionPerformed
        chatGptScreen();
    }//GEN-LAST:event_btn_chatgptActionPerformed

    private void btn_chatonlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chatonlineActionPerformed
        chatOnlineScreen();
    }//GEN-LAST:event_btn_chatonlineActionPerformed

    private void btn_miscochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_miscochesActionPerformed
        myVehiclesScrren();
    }//GEN-LAST:event_btn_miscochesActionPerformed

    private void btn_adminmodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminmodeActionPerformed
        adminMode();
    }//GEN-LAST:event_btn_adminmodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MyAccount dialog = new MyAccount(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_adminmode;
    private javax.swing.JButton btn_cerrarsesion;
    private javax.swing.JButton btn_chatgpt;
    private javax.swing.JButton btn_chatonline;
    private javax.swing.JButton btn_favoritos;
    private javax.swing.JButton btn_miscoches;
    private javax.swing.JButton btn_ppal;
    private javax.swing.JComboBox<String> cb_genero;
    private javax.swing.JComboBox<String> cb_nacionalidad;
    private javax.swing.JLabel edit_loginInfo;
    private javax.swing.JLabel edit_otherInfo;
    private javax.swing.JLabel edit_personalInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private com.toedter.calendar.JDateChooser jdc_fnacimiento;
    private javax.swing.JTextField txt_apel;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_newpass;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JLabel txt_nombrelog;
    private javax.swing.JTextField txt_passact;
    private javax.swing.JTextField txt_tlf;
    // End of variables declaration//GEN-END:variables

    private int id_user;
    private User usu;
    private Utils utils;
    private UsersController userDAO;
    private HashMap<String, String> paisesNacionalidades;

    private void init(int id_user) {
        this.id_user = id_user;
        this.utils = new Utils(this);
        this.userDAO = new UsersController();
        this.btn_adminmode.setVisible(false);
        rellenarCombo();
        iniciarUsuario();
        checkAdmin();
    }

    private void bloquearCampos() {
        txt_nombre.setEnabled(false);
        txt_apel.setEnabled(false);
        txt_mail.setEnabled(false);
        txt_tlf.setEnabled(false);
        txt_newpass.setEnabled(false);
        txt_passact.setEnabled(false);
        cb_genero.setEnabled(false);
        cb_nacionalidad.setEnabled(false);
        jdc_fnacimiento.setEnabled(false);
        txt_newpass.setText("");
        txt_passact.setText("");
        txt_nombrelog.setText(txt_nombre.getText());
    }

    private void iniciarUsuario() {
        usu = userDAO.read(id_user);
        bloquearCampos();
        Map<String, Integer> generos = new HashMap<>();
        generos.put("Masculino", 0);
        generos.put("Femenino", 1);
        generos.put("Otro", 2);
        cb_genero.setSelectedIndex(generos.get(usu.getGender()));
        cb_nacionalidad.setSelectedItem(usu.getNationality());
        jdc_fnacimiento.setDate(usu.getBirthdate());
        txt_nombrelog.setText(usu.getName());
        txt_nombre.setText(usu.getName());
        txt_apel.setText(usu.getSurname());
        txt_mail.setText(usu.getEmail());
        txt_tlf.setText(usu.getPhone());
    }

    private void actualizarUsuario() {
        if (controlExcepciones()) {
            if (controlPass()) {
                usu.setPass(txt_newpass.getText());
            }
            usu.setName(txt_nombre.getText());
            usu.setSurname(txt_apel.getText());
            usu.setPhone(txt_tlf.getText());
            usu.setEmail(txt_mail.getText());
            usu.setNationality(cb_nacionalidad.getSelectedItem().toString());
            usu.setGender(cb_genero.getSelectedItem().toString());
            usu.setBirthdate(jdc_fnacimiento.getDate());
            if(userDAO.update(usu)){
                utils.showMessage("Se han actualizado los datos correctamente");
            } else {
                utils.showMessage("Se ha producido un error al actualizar los datos. Intentalo nuevamente.");
            }
            bloquearCampos();          
        }
    }

    private boolean controlPass() {
        if (!txt_newpass.getText().trim().equals("") && !txt_passact.getText().trim().equals("")) {
            if (Boolean.parseBoolean(userDAO.readPass(usu.getEmail(), txt_passact.getText()).get(1))) {
                return true;
            } else {
                utils.showMessage("La contraseña actual introducida no es correcta. No se actualizará la contraseña");
            }
        }
        return false;
    }

    private boolean controlExcepciones() {
        if (!controlCampos()) {
            utils.showMessage("Rellene todos los campos");
            return false;
        } else if (!controlMail()) {
            utils.showMessage("Introduzca un email valido");
            return false;
        } else if (!controlTlf()) {
            utils.showMessage("Introduzca un telefono valido");
            return false;
        } else if (!controlBirthDate()) {
            utils.showMessage("Introduzca una fecha de nacimiento valida");
            return false;
        }
        return true;
    }

    private boolean controlCampos() {
        if (txt_nombre.getText().equals("")) {
            return false;
        } else if (txt_apel.getText().equals("")) {
            return false;
        } else if (txt_tlf.getText().equals("")) {
            return false;
        } else if (txt_mail.getText().equals("")) {
            return false;
        }
        return true;
    }

    private boolean controlBirthDate() {
        return jdc_fnacimiento.getDate() != null;
    }

    private boolean controlTlf() {
        return Pattern.compile("[0-9]{9}").matcher(txt_tlf.getText()).matches();
    }

    private boolean controlMail() {
        return Pattern.compile("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$").matcher(txt_mail.getText()).matches();
    }

    private void rellenarCombo() {
        paisesNacionalidades = utils.getPaisesNacionalidades();
        ArrayList<String> comboSort = new ArrayList<>();

        for (Map.Entry<String, String> entry : paisesNacionalidades.entrySet()) {
            comboSort.add(entry.getValue());
        }
        Collections.sort(comboSort);

        for (int i = 0; i < comboSort.size(); i++) {
            cb_nacionalidad.addItem(comboSort.get(i));
        }
    }

    private void cerrarSesion() {
        if(utils.showConfirmDialog("Estas seguro de que quiere cerrar la sesión?", "Cerrar Sesión") == 0){
            MainScreen main = (MainScreen) getParent();
            main.cerrarFrame();
            MainScreen mainScreen = new MainScreen(0);
            mainScreen.setVisible(true);
            this.setVisible(false);
        }
    }

    private void editPersonalInfo() {
        txt_nombre.setEnabled(true);
        txt_apel.setEnabled(true);
        txt_tlf.setEnabled(true);
    }

    private void editOtherInfo() {
        cb_genero.setEnabled(true);
        cb_nacionalidad.setEnabled(true);
        jdc_fnacimiento.setEnabled(true);
    }

    private void editLoginInfo() {
        txt_newpass.setEnabled(true);
        txt_passact.setEnabled(true);
        txt_mail.setEnabled(true);
    }

    private void favoritesScreen() {
        ScreenMyVehicles scr = new ScreenMyVehicles((Frame) getParent(), false, usu);
        scr.setVisible(true);
    }

    private void chatGptScreen() {
        Chat chat = new Chat(null, false);
        chat.setVisible(true);
    }

    private void chatOnlineScreen() {
        Chat chat = new Chat(null, false, id_user);
        chat.setVisible(true);
    }

    private void myVehiclesScrren() {
        ScreenMyVehicles scr = new ScreenMyVehicles((Frame) getParent(), false, id_user);
        scr.setVisible(true);
    }

    private void adminMode() {
        AdminScreen as = new AdminScreen((MainScreen) getParent(), false, id_user);
        as.setVisible(true);
        this.setVisible(false);
    }

    private void checkAdmin() {
        for (String arrayPermission : usu.getPermissions().split("-")) {            
            if (!arrayPermission.equals("user")) {      
                btn_adminmode.setVisible(true);              
            }
        }
    }
}