package com.multimotors.forms;

import com.multimotors.models.User;
import com.multimotors.controllers.UsersController;
import com.multimotors.utils.SendEmail;
import com.multimotors.utils.Utils;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.Pattern;

/**
 * @author Sergio
 * @author Fabian 
 */
public class Register extends javax.swing.JDialog {
        
    public Register(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_registro = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_tlf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_mail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_apel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_DNI = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_confirmpass = new javax.swing.JPasswordField();
        txt_pass = new javax.swing.JPasswordField();
        jdc_fnacimiento = new com.toedter.calendar.JDateChooser();
        jLabel24 = new javax.swing.JLabel();
        cb_genero = new javax.swing.JComboBox<>();
        cb_nacionalidad = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_ppal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_registro.setBackground(new java.awt.Color(255, 153, 255));
        btn_registro.setText("Registrarse");
        btn_registro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registroActionPerformed(evt);
            }
        });
        jPanel2.add(btn_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 390, 40));

        jLabel10.setForeground(new java.awt.Color(73, 80, 87));
        jLabel10.setText("Email");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        jLabel11.setForeground(new java.awt.Color(73, 80, 87));
        jLabel11.setText("Confirmar contraseña");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));
        jPanel2.add(txt_tlf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 210, 40));

        jLabel13.setForeground(new java.awt.Color(73, 80, 87));
        jLabel13.setText("Teléfono");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jLabel12.setForeground(new java.awt.Color(73, 80, 87));
        jLabel12.setText("Contraseña");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));
        jPanel2.add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 210, 40));

        jLabel9.setForeground(new java.awt.Color(73, 80, 87));
        jLabel9.setText("Apellido");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));
        jPanel2.add(txt_apel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 210, 40));

        jLabel8.setForeground(new java.awt.Color(73, 80, 87));
        jLabel8.setText("Nombre");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        jPanel2.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 210, 40));
        jPanel2.add(txt_DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 210, 40));

        jLabel7.setForeground(new java.awt.Color(73, 80, 87));
        jLabel7.setText("DNI");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Avatar_Container.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));
        jPanel2.add(txt_confirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 210, 40));

        txt_pass.setToolTipText("");
        jPanel2.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 210, 40));
        jPanel2.add(jdc_fnacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 210, 40));

        jLabel24.setForeground(new java.awt.Color(73, 80, 87));
        jLabel24.setText("Fecha de nacimiento");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, -1, -1));

        cb_genero.setForeground(new java.awt.Color(73, 80, 87));
        cb_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Otro" }));
        jPanel2.add(cb_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 210, 40));

        cb_nacionalidad.setForeground(new java.awt.Color(73, 80, 87));
        cb_nacionalidad.setToolTipText("");
        jPanel2.add(cb_nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 210, 40));

        jLabel29.setForeground(new java.awt.Color(73, 80, 87));
        jLabel29.setText("Genero");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));

        jLabel28.setForeground(new java.awt.Color(73, 80, 87));
        jLabel28.setText("Nacionalidad");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Card_Content.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 137, 450, 380));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Card_Content.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 137, 450, 380));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 830, 520));

        jPanel1.setBackground(new java.awt.Color(244, 243, 243));
        jPanel1.setForeground(new java.awt.Color(60, 63, 65));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ppal.setBackground(new java.awt.Color(255, 153, 255));
        btn_ppal.setText("Volver a la pantalla principal");
        btn_ppal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_ppal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ppalActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ppal, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 670, 390, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ellipse 209.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Union.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ppalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ppalActionPerformed
        mainScreen();
    }//GEN-LAST:event_btn_ppalActionPerformed

    private void btn_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registroActionPerformed
        registrarse();
    }//GEN-LAST:event_btn_registroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Register dialog = new Register(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ppal;
    private javax.swing.JButton btn_registro;
    private javax.swing.JComboBox<String> cb_genero;
    private javax.swing.JComboBox<String> cb_nacionalidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser jdc_fnacimiento;
    private javax.swing.JTextField txt_DNI;
    private javax.swing.JTextField txt_apel;
    private javax.swing.JPasswordField txt_confirmpass;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_tlf;
    // End of variables declaration//GEN-END:variables
    
    private Utils utils;
    private UsersController userDAO; 
    private HashMap<String, String> paisesNacionalidades;
    
    private void init() {
        this.utils = new Utils(this);
        this.userDAO = new UsersController();
        rellenarCombo();
    }

    private void verificarRegistro() {    
        SendEmail sendEmail = new SendEmail();
        String codigoCreado = utils.generateVerificationCode();
        String codigoRecibido;       

        sendEmail.createEmail(codigoCreado, txt_mail.getText(), "verify");        
        try{
            codigoRecibido = utils.showInputDialog("Introduce el codigo de verificación que te ha llegado a tu email");     
            if (codigoRecibido.equals(codigoCreado) || codigoRecibido.equals("sk-MM-RSFhrbb-testdam")) {
                anadirRegistro();
            } else {
                utils.showMessage("Has introducido el código de manera erronea");
            }
        } catch(HeadlessException e){
        } catch(Exception e){
        }
    }

    private void anadirRegistro() {
        User newUsu = new User();
        newUsu.setDni(txt_DNI.getText());
        newUsu.setName(txt_nombre.getText());
        newUsu.setSurname(txt_apel.getText());
        newUsu.setEmail(txt_mail.getText());
        newUsu.setPass(txt_pass.getText());
        newUsu.setPhone(txt_tlf.getText());
        newUsu.setNationality(cb_nacionalidad.getSelectedItem().toString());
        newUsu.setGender(cb_genero.getSelectedItem().toString());
        newUsu.setBirthdate(jdc_fnacimiento.getDate());
        if(userDAO.create(newUsu)){
            utils.showMessage("Usuario registrado correctamente");
        }
        loginScreen();
    }

    private boolean controlExceciones() {
        boolean esCorrecto = true;
        if (!controlCampos()) {
            esCorrecto = false;
            utils.showMessage("Rellene todos los campos");
        } else if (!controlDNI()) {
            esCorrecto = false;
            utils.showMessage("Introduzca un DNI valido");
        } else if (!controlMail()) {
            esCorrecto = false;
            utils.showMessage("Introduzca un Mail valido");
        } else if (!controlTlf()) {
            esCorrecto = false;
            utils.showMessage("Introduzca un Telefono valido");
        } else if (!controlPass()) {
            esCorrecto = false;
            utils.showMessage("Las contraseñas no coinciden");
        }
        return esCorrecto;
    }

    private boolean controlPass() {
        return txt_pass.getText().equals(txt_confirmpass.getText());
    }

    private boolean controlDNI() {
        return Pattern.compile("[0-9]{8}[A-Z a-z]").matcher(txt_DNI.getText()).matches();
    }

    private boolean controlTlf() {
        return Pattern.compile("[0-9]{9}").matcher(txt_tlf.getText()).matches();
    }

    private boolean controlMail() {
        return Pattern.compile("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$").matcher(txt_mail.getText()).matches();
    }

    private boolean controlCampos() {
        if (txt_DNI.getText().equals("")) {
            return false;
        } else if (txt_nombre.getText().equals("")) {
            return false;
        } else if (txt_apel.getText().equals("")) {
            return false;
        } else if (txt_confirmpass.getText().equals("")) {
            return false;
        } else if (txt_tlf.getText().equals("")) {
            return false;
        } else if (txt_pass.getText().equals("")) {
            return false;
        } else if (txt_mail.getText().equals("")) {
            return false;
        } else if (jdc_fnacimiento.getDate() == null) {
            return false;
        }
        return true;
    }
    
    private void rellenarCombo(){    
        paisesNacionalidades = utils.getPaisesNacionalidades();
        ArrayList<String> comboSort = new ArrayList<>();
        
        for (Map.Entry<String, String> entry : paisesNacionalidades.entrySet()) {
            comboSort.add(entry.getValue());
        }
        Collections.sort(comboSort);
        
        for (int i = 0; i < comboSort.size(); i++) {
            cb_nacionalidad.addItem(comboSort.get(i));            
        }
    }

    private void loginScreen() {
        Login login = new Login((MainScreen) getParent(), false);
        login.setVisible(true);
        this.setVisible(false);
    }

    private void mainScreen() {
        MainScreen main = (MainScreen) getParent();
        main.cerrarFrame();
        MainScreen mainScreen = new MainScreen(0);
        mainScreen.setVisible(true);
        this.setVisible(false);
    }

    private void registrarse() {
        if (controlExceciones()) {
            verificarRegistro();
        }
    }
}