package com.multimotors.forms;

import com.multimotors.models.User;
import com.multimotors.models.Vehicle;
import com.multimotors.controllers.FavoritesController;
import com.multimotors.controllers.VehiclesController;
import com.multimotors.utils.AWSFiles;
import com.multimotors.utils.Utils;
import java.awt.Component;
import java.awt.Frame;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 * @author Fabian
 * @author Sergio 
 */
public class ScreenMyVehicles extends javax.swing.JDialog {

    public ScreenMyVehicles(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    public ScreenMyVehicles(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents(); 
        setLocationRelativeTo(null);
        init(id);
    }
    
    public ScreenMyVehicles(java.awt.Frame parent, boolean modal, User user) {
        super(parent, modal);
        initComponents(); 
        setLocationRelativeTo(null);
        init(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        leftarrow = new javax.swing.JLabel();
        rightarrow = new javax.swing.JLabel();
        txt_photos = new javax.swing.JLabel();
        txt_renting = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        txt_price = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txt_license = new javax.swing.JLabel();
        txt_category = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txt_model = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txt_brand = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt_year = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txt_cc = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txt_traction = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_km = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_transmission = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_weight = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_fueltype = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_consumption = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_fueltank = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_quitarfavorito = new javax.swing.JButton();
        btn_comprar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_vehiculos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftarrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/svgexport-1.jpg"))); // NOI18N
        leftarrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftarrowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leftarrowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leftarrowMouseExited(evt);
            }
        });
        jPanel7.add(leftarrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 40, 150));

        rightarrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/svgexport-4.jpg"))); // NOI18N
        rightarrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rightarrowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rightarrowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rightarrowMouseExited(evt);
            }
        });
        jPanel7.add(rightarrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 160, 40, 150));

        txt_photos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_photosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_photosMouseExited(evt);
            }
        });
        jPanel7.add(txt_photos, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 450, 390));

        txt_renting.setForeground(new java.awt.Color(102, 102, 102));
        jPanel7.add(txt_renting, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 520, 70, 20));

        jLabel50.setText("Estado");
        jPanel7.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 500, 60, -1));

        txt_price.setForeground(new java.awt.Color(102, 102, 102));
        jPanel7.add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 590, 70, 20));

        jLabel52.setText("Precio");
        jPanel7.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 570, 60, -1));

        jLabel45.setText("Matrícula");
        jPanel7.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, 140, -1));

        txt_license.setForeground(new java.awt.Color(102, 102, 102));
        jPanel7.add(txt_license, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 590, 130, 20));

        txt_category.setForeground(new java.awt.Color(102, 102, 102));
        jPanel7.add(txt_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 520, 130, 20));

        jLabel48.setText("Categoría");
        jPanel7.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, 140, -1));

        txt_model.setForeground(new java.awt.Color(102, 102, 102));
        jPanel7.add(txt_model, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 590, 120, 20));

        jLabel44.setText("Modelo");
        jPanel7.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 570, 140, -1));

        jLabel41.setText("Marca");
        jPanel7.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 140, -1));

        txt_brand.setForeground(new java.awt.Color(102, 102, 102));
        jPanel7.add(txt_brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 130, 20));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/svgexport-11.jpg"))); // NOI18N
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, -1, -1));

        jLabel30.setText("Año del modelo");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 140, -1));

        txt_year.setForeground(new java.awt.Color(102, 102, 102));
        jPanel7.add(txt_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/svgexport-15.jpg"))); // NOI18N
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, -1, -1));

        jLabel33.setText("Potencia");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 140, -1));

        txt_cc.setForeground(new java.awt.Color(102, 102, 102));
        jPanel7.add(txt_cc, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, -1, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/svgexport-25.jpg"))); // NOI18N
        jPanel7.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, -1, -1));

        jLabel36.setText("Tracción");
        jPanel7.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 600, 140, -1));

        txt_traction.setForeground(new java.awt.Color(102, 102, 102));
        jPanel7.add(txt_traction, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 620, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/svgexport-12.jpg"))); // NOI18N
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, -1, -1));

        txt_km.setForeground(new java.awt.Color(102, 102, 102));
        jPanel7.add(txt_km, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, -1, -1));

        jLabel28.setText("Kilómetros");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 140, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/svgexport-14.jpg"))); // NOI18N
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, -1, -1));

        txt_transmission.setForeground(new java.awt.Color(102, 102, 102));
        jPanel7.add(txt_transmission, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, -1, -1));

        jLabel18.setText("Tipo de transmisión");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, 140, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/svgexport-27.jpg"))); // NOI18N
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, -1, -1));

        txt_weight.setForeground(new java.awt.Color(102, 102, 102));
        jPanel7.add(txt_weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 620, -1, -1));

        jLabel15.setText("Peso");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 600, 140, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/svgexport-13.jpg"))); // NOI18N
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        jLabel11.setText("Tipo gasolina");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 140, -1));

        txt_fueltype.setForeground(new java.awt.Color(102, 102, 102));
        jPanel7.add(txt_fueltype, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/svgexport-30.jpg"))); // NOI18N
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, -1));

        jLabel8.setText("Consumo medio");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 140, -1));

        txt_consumption.setForeground(new java.awt.Color(102, 102, 102));
        jPanel7.add(txt_consumption, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/svgexport-13.jpg"))); // NOI18N
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        jLabel5.setText("Capacidad del depósito");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 140, -1));

        txt_fueltank.setForeground(new java.awt.Color(102, 102, 102));
        jPanel7.add(txt_fueltank, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Datos técnicos");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 110, -1));
        jPanel7.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 580, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Datos básicos");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 110, -1));
        jPanel7.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 350, 10));

        btn_quitarfavorito.setBackground(new java.awt.Color(255, 153, 255));
        btn_quitarfavorito.setText("Quitar de favoritos");
        btn_quitarfavorito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_quitarfavorito.setEnabled(false);
        btn_quitarfavorito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitarfavoritoActionPerformed(evt);
            }
        });
        jPanel7.add(btn_quitarfavorito, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 570, 120, 40));

        btn_comprar.setBackground(new java.awt.Color(255, 153, 255));
        btn_comprar.setText("Comprar");
        btn_comprar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn_comprar.setEnabled(false);
        btn_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comprarActionPerformed(evt);
            }
        });
        jPanel7.add(btn_comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 500, 120, 40));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Card_Content.png"))); // NOI18N
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 450, 200));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Card_Content.png"))); // NOI18N
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 450, 190));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Card_Content.png"))); // NOI18N
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 450, 190));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Card_Content.png"))); // NOI18N
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 450, 190));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Card_Content.png"))); // NOI18N
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 450, 190));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setOpaque(true);
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 450, 90, 190));

        tb_vehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_vehiculos.setRowHeight(50);
        tb_vehiculos.setRowMargin(5);
        tb_vehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_vehiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_vehiculos);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 670, 390));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1220, 670));

        jPanel1.setBackground(new java.awt.Color(244, 243, 243));
        jPanel1.setForeground(new java.awt.Color(60, 63, 65));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/myacc_wp.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_photosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_photosMouseEntered
        setArrowsVisibility(true);
    }//GEN-LAST:event_txt_photosMouseEntered

    private void txt_photosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_photosMouseExited
        setArrowsVisibility(false);
    }//GEN-LAST:event_txt_photosMouseExited

    private void rightarrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightarrowMouseClicked
        righarrowclicked();
    }//GEN-LAST:event_rightarrowMouseClicked

    private void leftarrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftarrowMouseClicked
        leftarrowclicked();
    }//GEN-LAST:event_leftarrowMouseClicked

    private void rightarrowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightarrowMouseEntered
        rightarrow.setVisible(true);
    }//GEN-LAST:event_rightarrowMouseEntered

    private void leftarrowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftarrowMouseEntered
        leftarrow.setVisible(true);
    }//GEN-LAST:event_leftarrowMouseEntered

    private void rightarrowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightarrowMouseExited
        rightarrow.setVisible(false);
    }//GEN-LAST:event_rightarrowMouseExited

    private void leftarrowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftarrowMouseExited
        leftarrow.setVisible(false);
    }//GEN-LAST:event_leftarrowMouseExited

    private void tb_vehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_vehiculosMouseClicked
        cargarVehiculo();
    }//GEN-LAST:event_tb_vehiculosMouseClicked

    private void btn_quitarfavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitarfavoritoActionPerformed
        quitarDeFavoritos();
    }//GEN-LAST:event_btn_quitarfavoritoActionPerformed

    private void btn_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comprarActionPerformed
        comprarVehiculo();
    }//GEN-LAST:event_btn_comprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenMyVehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ScreenMyVehicles dialog = new ScreenMyVehicles(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_comprar;
    private javax.swing.JButton btn_quitarfavorito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel leftarrow;
    private javax.swing.JLabel rightarrow;
    private javax.swing.JTable tb_vehiculos;
    private javax.swing.JLabel txt_brand;
    private javax.swing.JLabel txt_category;
    private javax.swing.JLabel txt_cc;
    private javax.swing.JLabel txt_consumption;
    private javax.swing.JLabel txt_fueltank;
    private javax.swing.JLabel txt_fueltype;
    private javax.swing.JLabel txt_km;
    private javax.swing.JLabel txt_license;
    private javax.swing.JLabel txt_model;
    private javax.swing.JLabel txt_photos;
    private javax.swing.JLabel txt_price;
    private javax.swing.JLabel txt_renting;
    private javax.swing.JLabel txt_traction;
    private javax.swing.JLabel txt_transmission;
    private javax.swing.JLabel txt_weight;
    private javax.swing.JLabel txt_year;
    // End of variables declaration//GEN-END:variables
    
    private int imageIndex = 0;
    private int id_user;
    private User user;
    private Utils utils;
    private AWSFiles awsImages;
    private VehiclesController vehicleDAO;
    private FavoritesController favoriteDAO;
    private ArrayList<String> imagesVehicle;
    private HashMap<Integer, Vehicle> vehicles;
    private List<BufferedImage> images;
    
    private void init(){
        this.imageIndex = 0;
        this.utils = new Utils(this);
        this.awsImages = new AWSFiles();
        this.imagesVehicle = new ArrayList<>();
        this.vehicleDAO = new VehiclesController();
        this.favoriteDAO = new FavoritesController();
        this.leftarrow.setVisible(false);
        this.rightarrow.setVisible(false);    
    }
    
    private void init(int id){
        init();
        this.id_user = id;
        this.btn_comprar.setVisible(false);
        this.btn_quitarfavorito.setVisible(false);
        iniciarTabla(true);        
    }
        
    private void init(User user){
        init();
        this.id_user = user.getId();
        this.user = user;
        iniciarTabla(false);        
    }
    
    private void limpiarCampos(){
        txt_brand.setText("");
        txt_model.setText("");
        txt_category.setText("");
        txt_license.setText("");
        txt_renting.setText("");
        txt_price.setText("");
        txt_fueltank.setText("");
        txt_fueltype.setText("");
        txt_consumption.setText("");
        txt_km.setText("");
        txt_transmission.setText("");
        txt_weight.setText("");
        txt_year.setText("");
        txt_cc.setText("");
        txt_traction.setText("");
        txt_photos.setIcon(null);
    }
    
    private int getIdVehicleSelected(){
        try{
            return Integer.parseInt(String.valueOf(tb_vehiculos.getValueAt(tb_vehiculos.getSelectedRow(), 0)));
        } catch (NumberFormatException e){
            return 0;
        }
    }
    
    private void quitarDeFavoritos(){
        try{
            if(favoriteDAO.delete(id_user, getIdVehicleSelected())){
                utils.showMessage("Vehiculo eliminado de favoritos correctamente");
            } else {
                utils.showMessage("Error al eliminar de favoritos");
            }
            limpiarCampos();
            iniciarTabla(false);
            btn_comprar.setEnabled(false);
            btn_quitarfavorito.setEnabled(false);
        } catch (Exception e){
        }
    }
    
    private void comprarVehiculo(){
        try{
            ScreenBuyRent scr = new ScreenBuyRent((Frame) getParent(), false, user, vehicles.get(getIdVehicleSelected()));
            scr.setVisible(true);
            this.setVisible(false);
        } catch (Exception e){
        }
    }
    
    private void cargarVehiculo(){
        try{
            btn_comprar.setEnabled(true);
            btn_quitarfavorito.setEnabled(true);
            initVehicleData(vehicles.get(getIdVehicleSelected()));
        } catch (Exception e){
        }
    }
    
    private void iniciarTabla(boolean all) {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        if(all){
            vehicles = vehicleDAO.readAllForUserId(id_user);
        } else {
            vehicles = vehicleDAO.readFavorites(id_user);
        }	
        
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        modelo.addColumn("ID");
        modelo.addColumn("Vehiculo");
        modelo.addColumn("Combustible");
        modelo.addColumn("Kilometros");
        modelo.addColumn("Transmision");
        modelo.addColumn("Potencia");
        modelo.addColumn("Precio");

        for (Vehicle vehicle : vehicles.values()) {
            Object[] fila = new Object[7];
            fila[0] = vehicle.getId();
            fila[1] = vehicle.getBrand() + " " + vehicle.getModel();
            fila[2] = vehicle.getSpecs().getFuel_type();
            fila[3] = vehicle.getSpecs().getKilometres();
            fila[4] = vehicle.getSpecs().getTransmission_type();
            fila[5] = vehicle.getSpecs().getEngine_cc();
            fila[6] = vehicle.getPrice();
            modelo.addRow(fila);
        }
        tb_vehiculos.setModel(modelo);
        resizeColumnWidth(tb_vehiculos);
        
        for (int i = 0; i < tb_vehiculos.getColumnCount(); i++) {
            tb_vehiculos.getColumnModel().getColumn(i).setCellRenderer(tcr);
        }
        tb_vehiculos.getColumnModel().getColumn(0).setMaxWidth(0);
        tb_vehiculos.getColumnModel().getColumn(0).setMinWidth(0);
        tb_vehiculos.getColumnModel().getColumn(0).setPreferredWidth(0);
        tb_vehiculos.getColumnModel().getColumn(0).setResizable(false);
    }
    
    private void resizeColumnWidth(JTable table) {
        TableColumnModel columnModel = table.getColumnModel();
        
        for (int column = 0; column < table.getColumnCount(); column++) {
            int width = 150;
            
            for (int row = 0; row < table.getRowCount(); row++) {              
                TableCellRenderer renderer = table.getCellRenderer(row, column);
                Component comp = table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width + 1, width);
            }
            if (width > 300) {
                width = 300;
            }
            columnModel.getColumn(column).setPreferredWidth(width);
        }
    }

    private void initVehicleData(Vehicle v) {
        txt_brand.setText(v.getBrand());
        txt_model.setText(v.getModel());
        txt_category.setText(v.getCategory());
        txt_license.setText(v.getLicense_plate());
        txt_renting.setText(String.valueOf(v.getStatus()));
        txt_price.setText(String.valueOf(v.getPrice()) + " €");
        txt_fueltank.setText(String.valueOf(v.getSpecs().getFuel_tank()) + " L");
        txt_fueltype.setText(v.getSpecs().getFuel_type());
        txt_consumption.setText(String.valueOf(v.getSpecs().getConsumption()) + " L / 100km");
        txt_km.setText(String.valueOf(v.getSpecs().getKilometres()) + " km");
        txt_transmission.setText(v.getSpecs().getTransmission_type());
        txt_weight.setText(String.valueOf(v.getSpecs().getWeight()));
        txt_year.setText(String.valueOf(v.getSpecs().getModel_year()));
        txt_cc.setText(String.valueOf(v.getSpecs().getEngine_cc()) + " cv");
        txt_traction.setText(v.getSpecs().getTraction());
        
        initImages(v);
        putImage();
    }
    
    private void initImages(Vehicle v) {
        imagesVehicle.clear(); 
        String dato = v.getPhotos();
        if(dato.equals("") || dato.equals("null")){
            dato = "noimageavailable.jpg";
        }
        String[] imagenes = dato.split("-");
        imagesVehicle.addAll(Arrays.asList(imagenes));     
        images = awsImages.downloadImages(imagesVehicle);
    }

    private void putImage() {
        try{
            Image imgEscalada = images.get(imageIndex).getScaledInstance(txt_photos.getWidth(),txt_photos.getHeight(), Image.SCALE_SMOOTH);
            Icon iconoEscalado = new ImageIcon(imgEscalada);
            txt_photos.setIcon(iconoEscalado);
        } catch (Exception e){
        }
    }

    private void righarrowclicked() {
        imageIndex++;
        if (imageIndex >= imagesVehicle.size()) {
            imageIndex = 0;
        }
        putImage();    
    }

    private void leftarrowclicked() {
        imageIndex--;
        if (imageIndex < 0) {
            imageIndex = imagesVehicle.size() - 1;
        }
        putImage();    
    }

    private void setArrowsVisibility(boolean visible) {
        leftarrow.setVisible(visible);
        rightarrow.setVisible(visible);    
    }
}